dist: bionic

language: java

jdk: openjdk11

git:
  depth: false

addons:
  sonarcloud:
    organization: "octopus-prime-github"
    token:
      secure: "gefbEyX26XV6L93nzCcgoDRe2tMCrh4WfR78PjYJFoz4wT/UEOi26YkO9PB0Y6jc/3URphzycbGvRBmH2pMr671P3LY+mQ+axAfSzfhSw+ozCVIBY+woqLugliFN/8iWfOijtTNuvLXEvh6o9MbkaTRlunnbivvWoyvhyacBdIYTvtp4TIVH3Z4cH3Xx6IkfndUuOEAuQAW25lOkwGvF/6sslkhAslDsdJY0tSXuwMzWsH43F1T3nYxyFtaPUi4IqiEbJfWIUN4nmK2rOOtGRCwIz6zUWHBg2nZLg2CrJNYfPKOHdCOhI+5eVmUHYouPimSupJx3w6l3wFbGEbyPSmmlHf83dF3xTj16MKGUqc3HmoaiIdr2wctBd+68jzN9pQdqb9R2FEXrShn+hmqxWRBdbDmYptFl5nhI9CKCCL3N5ujE/qy1SiPqnq5DxQfTt65gI7Co+tra0VzOH+bgfFJMqSbKujfCuQOF+vgPOCpENBunEh0b/p6m765tdKyg9z2W5Hlo34JVFhexR3zYwDheuwxmw1O9pD5jWFeaaQ6aLU8CRitnkjSqeaG+z4Bxc1DR1kJFb0lhfscIub7ae7ZHkwWETsGa8SY7df3lgLHfXR/2+jhNydi7fcD0jVmaldh7D2QS6Tdh3Yz2zqKsiZNkzXhXXvW3OB8WYp8DC0w="

script:
  - ./gradlew clean build jacocoTestReport sonarqube

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.gradle'
    - '.gradle'
